### ISSUE TITLE
Very Poor Debugging Support

### ISSUE THREAD

**Issue by ProLoser** [jaredhoyt/cakephp-wizard#1]
I can't put die; or debug(); into the prepare/process or complete methods because of how the wizard works. It would be nice if at the very least placing debug or die could give some feedback on screen instead of merely redirecting (and therefore losing all the output)

**Comment by jaredhoyt** [comment]
The die() function should work anywhere in any application if the code is being executed.

Are you sure the callbacks are being hit?
